### ISSUE TITLE
Best way to disable littlecms compilation?

### ISSUE THREAD

**Issue by lilith** [kornelski/rust-lcms2-sys#1]
I'm building/linking littlecms2 using Conan, and (for now) I want to prevent this crate from building/linking the in-repo source.

**Comment by kornelski** [comment]
Make your version available via pkg-config

**Comment by kornelski** [comment]
Or set `LCMS2_LIB_DIR` 9d14e4e42eccdb89ca222c52ccab7bb4b4986078

**Comment by lilith** [comment]
Thanks
