### ISSUE TITLE
fPIC

### ISSUE THREAD

**Issue by lilith** [kornelski/rust-lcms2-sys#2]
Sometimes static compilation does not use -fPIC. 

Perhaps adding `c.pic(true)` would help? This is set in mozjpeg-sys

**Comment by lilith** [comment]
Nevermind, this is a bug with an older version of GCC (6). GCC 9 works

**Comment by kornelski** [comment]
For the record, I assume the `cc` crate sets `fPIC` by default, since Rust requires it.
